// GUY — Autonomous Coding Agent logic
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];

const STORAGE_KEY = 'guy_state_v042';

const defaultState = {
  github: { repo: 'thepotatoninjahost/Guy', branch: 'arena/01a0a37c-guy', connected: false, token: '' },
  agent: { status: 'idle', mode: 'awaiting task', progress: 0, uptimeSec: 862, tasksDone: 17, lines: 42700, skills: 24, plugins: 9, research: 163 },
  tasks: [
    { id:'t1', title:'FastAPI HN cache service', desc:'Scrape HN top stories, cache to SQLite, expose /top?limit=10', lang:'python', status:'running', progress:62, eta:'1m 12s' },
    { id:'t2', title:'Kotlin Flow debounce search', desc:'Android ViewModel with Flow debounce + StateFlow UI', lang:'kotlin', status:'queued', progress:0, eta:'~3m' },
    { id:'t3', title:'TS Canvas sparkline plugin', desc:'Zero-dep sparkline web component with ResizeObserver', lang:'javascript', status:'review', progress:88, eta:'40s' },
    { id:'t4', title:'Python CLI skill installer', desc:'Auto-register new skills from PyPI metadata at runtime', lang:'python', status:'queued', progress:0, eta:'~2m' },
  ],
  skills: [
    { name:'Python AsyncIO', cat:'python', lvl:92, pct:92, trend:'+4%' },
    { name:'FastAPI & Pydantic', cat:'python', lvl:84, pct:84, trend:'+2%' },
    { name:'JS Toolchain (Vite/TS)', cat:'javascript', lvl:88, pct:88, trend:'+5%' },
    { name:'React / DOM', cat:'javascript', lvl:76, pct:76, trend:'+3%' },
    { name:'Kotlin Coroutines', cat:'kotlin', lvl:71, pct:71, trend:'+7%' },
    { name:'Kotlin Flow & Channels', cat:'kotlin', lvl:68, pct:68, trend:'+6%' },
    { name:'SQLite & Caching', cat:'infra', lvl:81, pct:81, trend:'+1%' },
    { name:'Web Scraping', cat:'research', lvl:79, pct:79, trend:'+2%' },
    { name:'Code Review AI', cat:'agent', lvl:90, pct:90, trend:'+3%' },
    { name:'Research Synthesis', cat:'research', lvl:86, pct:86, trend:'+4%' },
    { name:'Plugin Runtime', cat:'agent', lvl:73, pct:73, trend:'+8%' },
    { name:'Git Automation', cat:'infra', lvl:77, pct:77, trend:'+2%' },
  ],
  plugins: [
    { name:'PyLance', desc:'Deep Python type inference & import graph', ver:'2.4.1', enabled:true, author:'guy/plugins', installs:'1.2k' },
    { name:'TS Morph', desc:'AST refactor & codemod engine', ver:'1.9.0', enabled:true, author:'guy/plugins', installs:'892' },
    { name:'Kotliner', desc:'Kotlin DSL + gradle sync helper', ver:'0.8.3', enabled:true, author:'community', installs:'521' },
    { name:'Researcher', desc:'Tavily/Brave live research aggregator', ver:'3.1.0', enabled:true, author:'guy/core', installs:'—' },
    { name:'Verifier', desc:'Self-review: lint, test, security scan', ver:'2.0.4', enabled:true, author:'guy/core', installs:'—' },
    { name:'Canvas Preview', desc:'Live artifact preview with hot reload', ver:'1.2.0', enabled:false, author:'guy/plugins', installs:'430' },
    { name:'Skill Forge', desc:'Auto-generates new skills from task history', ver:'0.6.0', enabled:true, author:'guy/core', installs:'—' },
    { name:'GH Sync', desc:'Branch, commit, PR automation', ver:'1.4.2', enabled:false, author:'guy/plugins', installs:'610' },
    { name:'Evolver', desc:'Cross-session capability evolution tracker', ver:'0.9.1', enabled:true, author:'guy/core', installs:'—' },
  ],
  researchResults: [
    { source:'kotlinlang.org • docs', title:'Coroutines: Flow is cold, Channel is hot — use StateFlow for UI', snippet:'StateFlow is a hot Flow that replays latest value. For search debounce use flow.debounce(300).distinctUntilChanged().flatMapLatest { api.query(it) }', relevance:'94%' },
    { source:'developer.android.com', title:'Best practices: ViewModel + Flow with lifecycle.repeatOnLifecycle', snippet:'Collect Flows in viewLifecycleOwner.repeatOnLifecycle to avoid leaks. Prefer stateIn(viewModelScope) for UI state.', relevance:'88%' },
    { source:'blog.jetbrains.com', title:'Kotlin 2.0: Coroutine debugger improvements', snippet:'New debugger can visualize concurrent coroutines and Flow emissions — useful for autonomous review step.', relevance:'81%' },
  ],
  artifacts: {
    python: {
      tabs: ['main.py','cache.py','test_main.py'],
      code: `# main.py — FastAPI HN cache (generated by GUY · iter v3)
from fastapi import FastAPI, Query
from cache import get_or_fetch
import asyncio

app = FastAPI(title="HN Top Cache", version="0.3.0")

@app.get("/top")
async def top(limit: int = Query(10, ge=1, le=50)):
    """Return top HN stories with SQLite KV cache (TTL 5m)."""
    items = await get_or_fetch(limit)
    return {"count": len(items), "items": items}

@app.get("/health")
async def health():
    return {"status": "ok", "agent": "GUY", "evolving": True}

# autonomous review: added Query validation + TTL jitter
# research injection: HN Algolia API > scraping for stability
`,
      review: '<strong>Self-review ✓</strong> — Added Query validation, TTL jitter (270-330s), and Algolia fallback. Tests: 5/5 passing. Ready for auto-push to <code>arena/01a0a37c-guy</code> if GH connected.'
    },
    javascript: {
      tabs: ['sparkline.ts','index.html','sparkline.test.ts'],
      code: `// sparkline.ts — zero-dep web component (GUY · iter v2)
class Sparkline extends HTMLElement {
  static observedAttributes = ["values","color"];
  #ro: ResizeObserver | null = null;
  connectedCallback(){
    this.attachShadow({mode:"open"});
    this.#render();
    this.#ro = new ResizeObserver(()=>this.#render());
    this.#ro.observe(this);
  }
  #render(){
    const vals = (this.getAttribute("values")||"").split(",").map(Number).filter(Boolean);
    const w = this.clientWidth||120, h = 32;
    const max = Math.max(...vals,1), min = Math.min(...vals,0);
    const path = vals.map((v,i)=>{
      const x = (i/(vals.length-1))*w;
      const y = h - ((v-min)/(max-min||1))*h;
      return \`\${i===0?"M":"L"} \${x} \${y}\`;
    }).join(" ");
    this.shadowRoot!.innerHTML = \`<svg viewBox="0 0 \${w} \${h}" width="\${w}" height="\${h}">
      <path d="\${path}" fill="none" stroke="\${this.getAttribute("color")||"#00ff88"}" stroke-width="2" stroke-linejoin="round"/>
    </svg>\`;
  }
}
customElements.define("x-sparkline", Sparkline);
`,
      review: '<strong>Review → iterate</strong> — Need ResizeObserver disconnect + empty-state. Agent will auto-iterate (max 5). Research: MDN custom elements best practices injected.'
    },
    kotlin: {
      tabs: ['SearchViewModel.kt','SearchRepository.kt','SearchScreen.kt'],
      code: `// SearchViewModel.kt — debounced search with Flow (GUY · iter v1)
class SearchViewModel(
  private val repo: SearchRepository
): ViewModel() {
  private val query = MutableStateFlow("")

  val uiState: StateFlow<SearchUiState> = query
    .debounce(300)
    .distinctUntilChanged()
    .flatMapLatest { q ->
      if (q.isBlank()) flowOf(SearchUiState.Idle)
      else repo.search(q)
        .map { SearchUiState.Success(it) as SearchUiState }
        .catch { emit(SearchUiState.Error(it.message)) }
        .onStart { emit(SearchUiState.Loading) }
    }
    .stateIn(viewModelScope, SharingStarted.WhileSubscribed(5000), SearchUiState.Idle)

  fun onQueryChange(v: String){ query.value = v }
}

sealed interface SearchUiState {
  data object Idle: SearchUiState
  data object Loading: SearchUiState
  data class Success(val items: List<Item>): SearchUiState
  data class Error(val msg: String?): SearchUiState
}
`,
      review: '<strong>Research injected ✓</strong> — Applied debounce+distinct+flatMapLatest pattern from kotlinlang.org. Next iteration: add repeatOnLifecycle in Compose collect.'
    }
  }
};

function loadState(){
  try{ const s=JSON.parse(localStorage.getItem(STORAGE_KEY)); return s? {...structuredClone(defaultState), ...s, skills: s.skills||defaultState.skills, plugins: s.plugins||defaultState.plugins}: structuredClone(defaultState)}catch{ return structuredClone(defaultState)}
}
let state = loadState();
function saveState(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }

let currentLang = 'python';
let currentTabIndex = 0;
let currentIter = 3;
let logPaused = false;
let agentTick = null;
let researchTick = null;

// NAV
function setScreen(id){
  $$('.screen').forEach(s=>s.classList.remove('active'));
  document.getElementById('screen-'+id).classList.add('active');
  $$('.nav-item,.bnav-item').forEach(b=>{
    b.classList.toggle('active', b.dataset.screen===id);
  });
  // close drawer on mobile
  $('#sidebar').classList.remove('open');
  $('#backdrop').classList.remove('show');
  window.scrollTo({top:0,behavior:'smooth'});
  if(id==='skills') drawChart();
}
$$('.nav-item,.bnav-item').forEach(b=> b.addEventListener('click', ()=> setScreen(b.dataset.screen)));

// sidebar
$('#menuBtn').addEventListener('click', ()=>{
  $('#sidebar').classList.toggle('open');
  $('#backdrop').classList.toggle('show', $('#sidebar').classList.contains('open'));
});
$('#backdrop').addEventListener('click', ()=>{
  $('#sidebar').classList.remove('open');
  $('#backdrop').classList.remove('show');
});
$('#collapseBtn')?.addEventListener('click', ()=>{
  $('#sidebar').classList.toggle('collapsed');
  $('#collapseBtn').textContent = $('#sidebar').classList.contains('collapsed') ? '› Expand' : '‹ Collapse';
});
$$('.card-head.collapsible').forEach(h=>{
  h.addEventListener('click', ()=>{
    const id = h.dataset.toggle;
    const body = document.getElementById(id);
    if(!body) return;
    const hidden = body.style.display==='none';
    body.style.display = hidden ? '' : 'none';
    h.classList.toggle('collapsed', !hidden);
  });
});

// language pills
$('#langPills').addEventListener('click', e=>{
  const b = e.target.closest('.pill');
  if(!b) return;
  $$('#langPills .pill').forEach(p=>p.classList.remove('active'));
  b.classList.add('active');
  currentLang = b.dataset.lang;
  renderArtifact();
});

// queue
function renderQueue(){
  const list = $('#queueList');
  const counts = { queued: state.tasks.filter(t=>t.status==='queued').length, running: state.tasks.filter(t=>t.status==='running').length };
  $('#queueCount').textContent = `${state.tasks.length} • ${counts.running} running`;
  $('#queueBadge').textContent = state.tasks.length;
  list.innerHTML = state.tasks.map(t=>`
    <div class="queue-item ${t.status==='running'?'active':''}">
      <div class="q-left">
        <div class="q-title">${t.title}</div>
        <div class="q-desc">${t.desc}</div>
        <div class="q-meta">
          <span class="badge ${t.lang}">${t.lang}</span>
          <span class="badge ${t.status==='running'?'running':t.status==='review'?'review':t.status==='done'?'done':'queued'}">${t.status}</span>
        </div>
      </div>
      <div class="q-right">
        <div class="q-progress"><i style="width:${t.progress}%"></i></div>
        <span class="q-time">${t.eta}</span>
      </div>
    </div>
  `).join('');
}

// logs
const logLines = [
  `[09:41:02] <span class="log-level sys">SYS</span> <span class="log-msg">GUY kernel boot • indigo/dayglow theme • Galaxy S25 viewport 360×780</span>`,
  `[09:41:03] <span class="log-level info">INFO</span> <span class="log-msg">Research engine: Tavily (active) • auto-research enabled</span>`,
  `[09:41:05] <span class="log-level info">INFO</span> <span class="log-msg">Loaded 24 skills • avg proficiency 71% • 9 plugins (6 active)</span>`,
  `[09:41:08] <span class="log-level sys">PLAN</span> <span class="log-msg">Task #t1 “FastAPI HN cache service” → phases: research → plan → code → review → iterate</span>`,
];

function appendLog(html){
  if(logPaused) return;
  const stream = $('#logStream');
  const div = document.createElement('div');
  div.className='log-line';
  const now = new Date();
  const ts = now.toTimeString().slice(0,8);
  // if html already includes timestamp, use as is
  if(html.startsWith('[')){
    div.innerHTML = `<span class="log-time">${html.slice(1,9)}</span>${html.slice(10)}`;
  } else {
    div.innerHTML = `<span class="log-time">${ts}</span> ${html}`;
  }
  stream.appendChild(div);
  // keep max 140 lines
  while(stream.children.length>140) stream.removeChild(stream.firstChild);
  stream.scrollTop = stream.scrollHeight;
  // also count
  state.agent.research = Math.min(999, state.agent.research + (Math.random()<0.12?1:0));
}

function initLogs(){
  const s = $('#logStream');
  s.innerHTML = logLines.map(l=>`<div class="log-line"><span class="log-time">${l.slice(1,9)}</span>${l.slice(10)}</div>`).join('');
  s.scrollTop = s.scrollHeight;
}
$('#pauseLogBtn').addEventListener('click', ()=>{
  logPaused = !logPaused;
  $('#pauseLogBtn').textContent = logPaused ? '▶' : '⏸';
  toast(logPaused ? 'Log stream paused' : 'Log stream resumed');
});
$('#clearLogBtn').addEventListener('click', ()=>{
  $('#logStream').innerHTML='';
  toast('Logs cleared');
});

const autonomousMessages = [
  `<span class="log-level info">RESEARCH</span> <span class="log-msg">Tavily query: “Kotlin coroutines best practices 2024 + Flow vs Channel” → 3 sources, relevance 88%</span>`,
  `<span class="log-level info">INFO</span> <span class="log-msg">Skill evolved: Kotlin Flow & Channels 68% → 71% (+3%) • learning from research</span>`,
  `<span class="log-level info">CODE</span> <span class="log-msg">Writing SearchViewModel.kt — debounce(300) + distinctUntilChanged + flatMapLatest</span>`,
  `<span class="log-level warn">REVIEW</span> <span class="log-msg">Self-review: missing repeatOnLifecycle in Compose — scheduling iteration v2</span>`,
  `<span class="log-level sys">PLUGIN</span> <span class="log-msg">Skill Forge: registered new capability “Compose Lifecycle” (pending proficiency 42%)</span>`,
  `<span class="log-level info">CODE</span> <span class="log-msg">Iterating sparkline.ts — added ResizeObserver cleanup + empty state path</span>`,
  `<span class="log-level info">RESEARCH</span> <span class="log-msg">Brave Search: “FastAPI SQLite cache TTL jitter” → 2 snippets added to knowledge graph</span>`,
  `<span class="log-level info">INFO</span> <span class="log-msg">Auto-committing artifact to arena/01a0a37c-guy (dry-run — GH offline)</span>`,
  `<span class="log-level sys">EVOLVE</span> <span class="log-msg">Cross-session evolution: +1 skill, proficiency avg 71% → 72% • next session will retain</span>`,
  `<span class="log-level info">INFO</span> <span class="log-msg">Task #t3 moved to review (88%) • awaiting human approval or auto-merge in 40s</span>`,
];

let autoIdx = 0;
function tickAgent(){
  const msg = autonomousMessages[autoIdx % autonomousMessages.length];
  appendLog(msg);
  autoIdx++;
  // animate agent progress + status
  const statuses = [
    { status:'CODING', mode:'writing code', cls:'coding', p: 62 },
    { status:'RESEARCHING', mode:'live web research', cls:'research', p: 71 },
    { status:'REVIEWING', mode:'self-review', cls:'coding', p: 88 },
    { status:'CODING', mode:'iterating v2', cls:'coding', p: 44 },
    { status:'IDLE', mode:'awaiting task', cls:'idle', p: 0 },
  ];
  const s = statuses[autoIdx % statuses.length];
  setAgentStatus(s.status, s.mode, s.cls, s.p);
  // task progress simulation
  state.tasks.forEach(t=>{
    if(t.status==='running' && Math.random()<0.6){
      t.progress = Math.min(98, t.progress + Math.floor(Math.random()*6)+1);
      if(t.progress>90) t.status='review';
    }
    if(t.status==='review' && Math.random()<0.15) t.status='done';
    if(t.status==='done' && t.progress<100) t.progress=100;
  });
  renderQueue();
  // evolution: every ~8 ticks evolve a skill
  if(autoIdx % 8 === 0){
    evolveRandomSkill();
  }
  saveState();
}
function setAgentStatus(text, mode, cls, progress){
  $('#agentStatusText').textContent = text;
  $('#agentMode').textContent = mode;
  $('#sidebarStatusDot').className = 'status-dot '+cls;
  $('#headerLiveDot').style.background = cls==='coding'? 'var(--amber)': cls==='research'? '#38bdf8':'var(--glow)';
  $('#headerLiveDot').style.boxShadow = cls==='coding'? '0 0 8px var(--amber)': cls==='research'? '0 0 8px #38bdf8':'0 0 8px var(--glow)';
  $('#agentProgress').style.width = progress+'%';
  $('#agentPulse').style.background = cls==='idle'? 'var(--glow)': cls==='coding'? 'var(--amber)':'#38bdf8';
}

// artifact viewer
function renderArtifact(){
  const data = state.artifacts[currentLang];
  if(!data) return;
  const tabsEl = $('#artifactTabs');
  tabsEl.innerHTML = data.tabs.map((t,i)=>`<button class="tab ${i===currentTabIndex?'active':''}" data-i="${i}">${t}</button>`).join('');
  tabsEl.querySelectorAll('.tab').forEach(b=>{
    b.addEventListener('click', ()=>{
      currentTabIndex = parseInt(b.dataset.i);
      renderArtifact();
    });
  });
  // code content per tab — for demo we show same code for first tab, placeholder for others
  let code = data.code;
  if(currentTabIndex===1){
    if(currentLang==='python') code = `# cache.py — KV cache with TTL jitter (GUY)
import sqlite3, time, json, random
DB="cache.db"
def get_or_fetch(limit:int):
    ttl = 300 + random.randint(-30,30)
    # ... SQLite get/set with expiry
    return []`;
    if(currentLang==='javascript') code = `<!-- index.html preview -->\n<x-sparkline values="4,7,3,9,5,8,2" color="#00ff88"></x-sparkline>\n<script type="module" src="./sparkline.ts"></script>`;
    if(currentLang==='kotlin') code = `// SearchRepository.kt\ninterface SearchRepository {\n  fun search(q: String): Flow<List<Item>>\n}\n// impl uses Ktor + Flow\n`;
  }
  if(currentTabIndex===2){
    if(currentLang==='python') code = `# test_main.py\nfrom fastapi.testclient import TestClient\nfrom main import app\nclient=TestClient(app)\ndef test_top():\n    r=client.get("/top?limit=2")\n    assert r.status_code==200\n`;
    if(currentLang==='javascript') code = `// sparkline.test.ts\nimport {expect, test} from "vitest"\n// tests for ResizeObserver cleanup\n`;
    if(currentLang==='kotlin') code = `@Composable\nfun SearchScreen(vm: SearchViewModel){\n  val state by vm.uiState.collectAsStateWithLifecycle()\n  // ...\n}`;
  }
  $('#codeBlock code').textContent = code;
  $('#artifactMeta').textContent = `${currentLang} • v${currentIter} • ${currentLang==='python'?2: currentLang==='javascript'?2:1} iterations`;
  // iteration pills
  const iterRow = $('#iterationRow');
  iterRow.innerHTML = Array.from({length: currentIter}, (_,i)=> `<button class="iter-pill ${i===currentIter-1?'active':''}" data-iter="${i+1}">v${i+1} ${i===currentIter-1?'• current':''}</button>`).join('');
  iterRow.querySelectorAll('.iter-pill').forEach(b=>{
    b.addEventListener('click', ()=>{
      const v = parseInt(b.dataset.iter);
      currentIter = v;
      // simulate earlier version truncation
      renderArtifact();
      toast('Switched to iteration v'+v);
    });
  });
  $('#reviewBox').innerHTML = data.review;
  // highlight-ish: keep monospace
}

$('#copyCodeBtn').addEventListener('click', ()=>{
  const txt = $('#codeBlock code').textContent;
  navigator.clipboard.writeText(txt).then(()=> toast('Code copied to clipboard'));
});

// skills & plugins
function renderSkills(){
  const grid = $('#skillGrid');
  grid.innerHTML = state.skills.map(s=>`
    <div class="skill-card ${s.pct>=88?'evolving':''}">
      <div class="skill-top">
        <div>
          <div class="skill-name">${s.name}</div>
          <div class="skill-cat">${s.cat}</div>
        </div>
        <span class="skill-lvl ${s.pct>=90?'max':''}">Lv ${Math.floor(s.pct/10)}</span>
      </div>
      <div class="skill-bar"><div class="skill-fill" style="width:${s.pct}%"></div></div>
      <div class="skill-foot">
        <span>${s.pct}% proficiency</span>
        <span class="skill-trend">${s.trend}</span>
      </div>
    </div>
  `).join('');
}
function renderPlugins(){
  const table = $('#pluginTable');
  table.innerHTML = state.plugins.map(p=>`
    <div class="plugin-row">
      <div class="p-info">
        <div class="p-name">${p.name} <span class="badge">${p.ver}</span></div>
        <div class="p-desc">${p.desc}</div>
        <div class="p-meta"><span>by ${p.author}</span><span>• ${p.installs} installs</span></div>
      </div>
      <div class="p-actions">
        <div class="toggle ${p.enabled?'on':''}" data-plugin="${p.name}" role="switch" aria-checked="${p.enabled}"></div>
      </div>
    </div>
  `).join('');
  table.querySelectorAll('.toggle').forEach(t=>{
    t.addEventListener('click', ()=>{
      const name = t.dataset.plugin;
      const pl = state.plugins.find(x=>x.name===name);
      if(pl){ pl.enabled = !pl.enabled; saveState(); renderPlugins(); toast(`${pl.name} ${pl.enabled?'enabled':'disabled'}`); }
    });
  });
}
function evolveRandomSkill(){
  const idx = Math.floor(Math.random()*state.skills.length);
  const s = state.skills[idx];
  s.pct = Math.min(99, s.pct + Math.floor(Math.random()*3)+1);
  s.trend = `+${Math.floor(Math.random()*4)+1}%`;
  // occasionally add new skill
  if(Math.random()<0.18 && state.skills.length<28){
    const newSkills = [
      { name:'Kotlin Multiplatform', cat:'kotlin', lvl:42, pct:42, trend:'new' },
      { name:'WASM Preview', cat:'javascript', lvl:38, pct:38, trend:'new' },
      { name:'Vector Caching', cat:'infra', lvl:45, pct:45, trend:'new' },
      { name:'Prompt Synthesis', cat:'agent', lvl:50, pct:50, trend:'new' },
    ];
    const pick = newSkills[Math.floor(Math.random()*newSkills.length)];
    if(!state.skills.find(x=>x.name===pick.name)){
      state.skills.push(pick);
      state.agent.skills = state.skills.length;
      toast('New skill acquired: '+pick.name+' — created at runtime');
      // timeline
      addEvolution(`Acquired “${pick.name}”`, `Agent registered new skill via Skill Forge plugin • proficiency ${pick.pct}%`);
    }
  }
  saveState();
  renderSkills();
  drawChart();
  appendLog(`<span class="log-level sys">EVOLVE</span> <span class="log-msg">Skill “${s.name}” leveled → ${s.pct}% (${s.trend})</span>`);
}
$('#acquireSkillBtn').addEventListener('click', ()=>{
  evolveRandomSkill();
  toast('Researching new skill…');
});

function addEvolution(title, desc){
  const tl = $('#evolutionTimeline');
  const el = document.createElement('div');
  el.className='evo-item';
  el.innerHTML=`<span class="evo-dot"></span><div class="evo-content"><div class="evo-title">${title}</div><div class="evo-desc">${desc}</div><div class="evo-time">just now • session #${Math.floor(Math.random()*20)+40}</div></div>`;
  tl.prepend(el);
  while(tl.children.length>5) tl.removeChild(tl.lastChild);
}
function initEvolutionTimeline(){
  const items = [
    { title:'Plugin “Verifier v2.0.4” auto-updated', desc:'Added security scan (pip-audit, npm audit) to review phase • applied to 3 tasks', time:'2m ago • session #42' },
    { title:'Skill “Research Synthesis” 82% → 86%', desc:'Learned Tavily deep-research pattern from 12 web results', time:'8m ago • session #42' },
    { title:'Acquired “Plugin Runtime” 65% → 73%', desc:'Agent wrote its own plugin loader with hot-swap capability', time:'18m ago • session #41' },
  ];
  $('#evolutionTimeline').innerHTML = items.map(it=>`<div class="evo-item"><span class="evo-dot"></span><div class="evo-content"><div class="evo-title">${it.title}</div><div class="evo-desc">${it.desc}</div><div class="evo-time">${it.time}</div></div></div>`).join('');
}

// chart
function drawChart(){
  const c = document.getElementById('acqChart');
  if(!c) return;
  const ctx = c.getContext('2d');
  const w = c.width, h=c.height;
  ctx.clearRect(0,0,w,h);
  // grid
  ctx.strokeStyle='rgba(255,255,255,0.06)';
  ctx.lineWidth=1;
  for(let i=0;i<4;i++){ const y= 14 + i*32; ctx.beginPath(); ctx.moveTo(28,y); ctx.lineTo(w-10,y); ctx.stroke(); }
  // data: skills, plugins, research over 7 sessions
  const skills = [12,14,16,18,20,22,24];
  const plugins = [3,4,5,6,7,8,9];
  const research = [60,80,95,120,138,150,163];
  // normalize research to 0-100 for height
  const normResearch = research.map(v=> (v/200)*100 );
  function drawLine(data, color, fill){
    const max = 100;
    const xStep = (w-40)/ (data.length-1);
    ctx.beginPath();
    data.forEach((v,i)=>{
      const x = 30 + i*xStep;
      const y = h-22 - (v/max)*(h-48);
      if(i===0) ctx.moveTo(x,y); else ctx.lineTo(x,y);
    });
    ctx.strokeStyle=color; ctx.lineWidth=2.4; ctx.lineJoin='round'; ctx.stroke();
    if(fill){
      ctx.lineTo(30 + (data.length-1)*xStep, h-22);
      ctx.lineTo(30, h-22);
      ctx.closePath();
      ctx.fillStyle=fill; ctx.fill();
    }
    // dots
    data.forEach((v,i)=>{
      const x = 30 + i*xStep;
      const y = h-22 - (v/max)*(h-48);
      ctx.beginPath(); ctx.arc(x,y,3,0,Math.PI*2); ctx.fillStyle=color; ctx.fill();
      ctx.beginPath(); ctx.arc(x,y,5,0,Math.PI*2); ctx.strokeStyle='rgba(255,255,255,0.15)'; ctx.lineWidth=1; ctx.stroke();
    });
  }
  drawLine(normResearch, '#fbbf24', 'rgba(251,191,36,0.08)');
  drawLine(plugins.map(v=> v/0.3 ), '#6366f1', 'rgba(99,102,241,0.12)'); // scale plugins 9*... approx
  // for visibility scale plugins to 0-100
  const pluginNorm = plugins.map(v=> (v/12)*100 );
  // redraw plugins correctly
  // clear and redraw all properly:
  ctx.clearRect(0,0,w,h);
  for(let i=0;i<4;i++){ const y= 14 + i*32; ctx.beginPath(); ctx.moveTo(28,y); ctx.lineTo(w-10,y); ctx.stroke(); }
  drawLine(normResearch, '#fbbf24', 'rgba(251,191,36,0.08)');
  drawLine(pluginNorm, '#6366f1', 'rgba(99,102,241,0.12)');
  drawLine(skills.map(v=> (v/30)*100 ), '#00ff88', 'rgba(0,255,136,0.14)');
  // labels
  ctx.fillStyle='#64748b'; ctx.font='9px JetBrains Mono'; ctx.fillText('S36',30,h-6); ctx.fillText('S42', w-30, h-6);
}

// settings github
function updateGithubUI(){
  const connected = state.github.connected;
  const dot = connected? 'on':'';
  $('#githubStatus').className='github-status '+dot;
  $('#githubStatus').innerHTML = `<i></i> ${connected?'connected':'offline'}`;
  $('#settingsGithubStatus').className='github-status '+dot;
  $('#settingsGithubStatus').innerHTML = `<i></i> ${connected?'connected':'offline'}`;
  $('#githubNavDot').className = 'nav-dot '+(connected?'on':'');
  $('#githubRepoLabel').textContent = connected? state.github.repo : 'not connected';
  $('#githubBranchLabel').textContent = connected? state.github.branch : '—';
  $('#ghRepo').value = state.github.repo;
  $('#ghBranch').value = state.github.branch;
  $('#syncRow').innerHTML = connected? `<span><i class="dot green"></i> Last sync: just now • 17 commits</span><span class="dim">• webhook active</span>` : `<span><i class="dot green" style="background:var(--text-faint)"></i> Last sync: never</span><span class="dim">• webhook idle</span>`;
  $('#apiGhState').textContent = state.github.token? '● active' : '○ not set';
  $('#apiGhState').className = 'key-state '+(state.github.token?'ok':'');
  $('#statTasks').textContent = state.agent.tasksDone;
  $('#statLines').textContent = (state.agent.lines/1000).toFixed(1)+'k';
  $('#statSkills').textContent = state.agent.skills;
  $('#statPlugins').textContent = state.agent.plugins;
  $('#statResearch').textContent = state.agent.research;
  saveState();
}
$('#connectGhBtn').addEventListener('click', ()=>{
  const repo = $('#ghRepo').value.trim() || 'thepotatoninjahost/Guy';
  const branch = $('#ghBranch').value;
  const token = $('#ghToken').value.trim();
  state.github.repo = repo; state.github.branch = branch; state.github.token = token;
  // simulate connect
  $('#connectGhBtn').textContent='⟳ CONNECTING…';
  $('#connectGhBtn').disabled=true;
  appendLog(`<span class="log-level sys">GITHUB</span> <span class="log-msg">Testing connection to ${repo}@${branch}…</span>`);
  setTimeout(()=>{
    state.github.connected = true;
    state.agent.plugins = state.plugins.filter(p=>p.enabled).length;
    updateGithubUI();
    $('#connectGhBtn').textContent='✓ CONNECTED';
    setTimeout(()=>{ $('#connectGhBtn').textContent='↯ CONNECT & TEST'; $('#connectGhBtn').disabled=false; },1200);
    toast('GitHub connected — auto-push enabled');
    appendLog(`<span class="log-level info">GITHUB</span> <span class="log-msg">Connected to ${repo}@${branch} • webhook registered • 17 commits synced</span>`);
    saveState();
  }, 1100);
});
$('#toggleTokenBtn').addEventListener('click', ()=>{
  const inp = $('#ghToken');
  inp.type = inp.type==='password'?'text':'password';
});
$('#ghRepo').addEventListener('change', e=>{ state.github.repo=e.target.value; saveState(); updateGithubUI(); });
$('#ghBranch').addEventListener('change', e=>{ state.github.branch=e.target.value; saveState(); updateGithubUI(); });
$('#ghToken').addEventListener('input', e=>{ state.github.token=e.target.value; saveState(); updateGithubUI(); });

// research engine
$('#engineGrid').addEventListener('click', e=>{
  const card = e.target.closest('.engine-card');
  if(!card) return;
  $$('.engine-card').forEach(c=>c.classList.remove('active'));
  card.classList.add('active');
  const engine = card.dataset.engine;
  $('#researchEngineLabel').textContent = (engine==='tavily'?'Tavily': engine==='brave'?'Brave Search': engine==='exa'?'Exa AI':'Serper')+' • live';
  appendLog(`<span class="log-level sys">RESEARCH</span> <span class="log-msg">Research engine switched to ${engine} • next query will use new engine</span>`);
  toast('Research engine: '+engine);
});
// API keys visibility
$$('.key-row .btn').forEach(btn=>{
  btn.addEventListener('click', ()=>{
    const inp = btn.previousElementSibling.querySelector('input');
    if(inp) inp.type = inp.type==='password'?'text':'password';
  });
});

// task submission
$('#deployBtn').addEventListener('click', ()=>{
  const prompt = $('#taskInput').value.trim();
  if(!prompt){
    toast('Describe a task first');
    $('#taskInput').focus();
    return;
  }
  const pri = document.querySelector('[data-pri].active')?.dataset.pri || 'normal';
  const title = prompt.slice(0,54) + (prompt.length>54?'…':'');
  const id = 't'+Date.now();
  const task = { id, title, desc: prompt.slice(0,96), lang: currentLang, status: 'queued', progress: 0, eta: pri==='urgent'?'~1m':'~3m' };
  state.tasks.unshift(task);
  if(state.tasks.length>8) state.tasks.pop();
  renderQueue();
  $('#taskInput').value='';
  toast('Task queued — agent will pick it up autonomously');
  appendLog(`<span class="log-level info">QUEUE</span> <span class="log-msg">New task #${id} queued [${currentLang}] • priority ${pri} • “${title}”</span>`);
  // auto-start after short delay
  setTimeout(()=>{
    const t = state.tasks.find(x=>x.id===id);
    if(t){ t.status='running'; t.progress=4; appendLog(`<span class="log-level sys">AGENT</span> <span class="log-msg">Picked up #${id} — researching → planning → coding</span>`); setAgentStatus('RESEARCHING','researching task', 'research', 14); renderQueue(); }
  }, 900);
  // simulate code artifact switching to language
  renderArtifact();
  saveState();
});
$('#taskInput').addEventListener('keydown', e=>{
  if((e.metaKey||e.ctrlKey) && e.key==='Enter') $('#deployBtn').click();
});

// autonomy sliders
$('#autonomyRange').addEventListener('input', e=>{ $('#autonomyVal').textContent = e.target.value+' / 10'; });
$('#iterRange').addEventListener('input', e=>{ $('#iterVal').textContent = e.target.value; });

// research panel rotation
const researchQueries = [
  '“Kotlin coroutines best practices 2024 + Flow vs Channel”',
  '“FastAPI SQLite cache TTL jitter pattern”',
  '“TypeScript ResizeObserver cleanup + custom elements”',
  '“PyPI skill auto-registration runtime plugins”',
  '“Tavily vs Brave Search for agentic RAG 2024”',
];
let rqIdx=0;
function rotateResearch(){
  rqIdx = (rqIdx+1)%researchQueries.length;
  $('#researchQueryText').textContent = researchQueries[rqIdx];
  // also rotate results
  if(state.researchResults.length){
    const first = state.researchResults.shift();
    state.researchResults.push(first);
    renderResearch();
  }
  $('#knowledgeAdded').textContent = `+${Math.floor(Math.random()*4)+1} snippets`;
}
function renderResearch(){
  $('#researchResults').innerHTML = state.researchResults.map(r=>`
    <div class="r-card">
      <div class="r-head"><span class="r-source">${r.source}</span><span class="r-relevance">${r.relevance} match</span></div>
      <div class="r-title">${r.title}</div>
      <div class="r-snippet">${r.snippet}</div>
    </div>
  `).join('');
}

// stats uptime
let uptime = state.agent.uptimeSec;
setInterval(()=>{
  uptime++;
  const h = String(Math.floor(uptime/3600)).padStart(2,'0');
  const m = String(Math.floor((uptime%3600)/60)).padStart(2,'0');
  const s = String(uptime%60).padStart(2,'0');
  $('#statUptime').textContent = `${h}:${m}:${s}`;
  state.agent.uptimeSec = uptime;
},1000);

// toasts
function toast(msg){
  const stack = $('#toastStack');
  const el = document.createElement('div');
  el.className='toast';
  el.textContent = msg;
  stack.appendChild(el);
  setTimeout(()=>{ el.style.opacity='0'; el.style.transform='translateY(4px)'; setTimeout(()=>el.remove(),300); },2600);
}

// init
function init(){
  renderQueue();
  initLogs();
  renderArtifact();
  renderSkills();
  renderPlugins();
  renderResearch();
  initEvolutionTimeline();
  updateGithubUI();
  drawChart();
  // initial agent status
  setAgentStatus('CODING','writing code','coding',62);
  // intervals
  agentTick = setInterval(tickAgent, 2200);
  researchTick = setInterval(rotateResearch, 5200);
  // log streaming warmth
  setTimeout(()=>appendLog(`<span class="log-level info">INFO</span> <span class="log-msg">Artifact viewer: main.py v3 ready • 2 iterations • review passed</span>`), 800);
  // handle GH token prefill
  if(state.github.token) $('#ghToken').value = state.github.token;
  if(state.github.token) $('#apiGhToken').value = state.github.token;

  // responsive chart redraw on resize
  window.addEventListener('resize', ()=> drawChart());
  // save periodically
  setInterval(saveState, 3000);
}
document.addEventListener('DOMContentLoaded', init);

// visibility: if page hidden, pause heavy ticks
document.addEventListener('visibilitychange', ()=>{
  if(document.hidden){ logPaused=true; } else { logPaused=false; }
});
